#!/usr/bin/env python3
"""Bundle site/index.html + assets into a single file://-friendly standalone HTML."""

from __future__ import annotations

import base64
import mimetypes
import re
import sys
from pathlib import Path

SITE = Path(__file__).resolve().parent
INDEX = SITE / "index.html"
OUT = SITE / "interest-group-standalone.html"

MIME = {
    ".woff2": "font/woff2",
    ".woff": "font/woff",
    ".js": "text/javascript",
    ".jsx": "text/javascript",
    ".jpg": "image/jpeg",
    ".jpeg": "image/jpeg",
    ".png": "image/png",
    ".svg": "image/svg+xml",
}


def data_url(path: Path) -> str:
    ext = path.suffix.lower()
    mime = MIME.get(ext) or mimetypes.guess_type(path.name)[0] or "application/octet-stream"
    b64 = base64.b64encode(path.read_bytes()).decode("ascii")
    return f"data:{mime};base64,{b64}"


def escape_script(text: str) -> str:
    return re.sub(r"</script", r"<\\/script", text, flags=re.I)


def inline_scripts(html: str) -> str:
    pattern = re.compile(
        r'<script\b([^>]*?)\bsrc="(assets/[^"]+)"([^>]*)>\s*</script>',
        re.I,
    )

    def repl(m: re.Match) -> str:
        pre, src, post = m.group(1), m.group(2), m.group(3)
        path = SITE / src
        if not path.is_file():
            raise FileNotFoundError(f"Missing script asset: {src}")
        body = escape_script(path.read_text(encoding="utf-8"))
        attrs = (pre + post).strip()
        attr_str = f" {attrs}" if attrs else ""
        return f"<script{attr_str}>\n{body}\n</script>"

    return pattern.sub(repl, html)


def embed_css_asset_urls(html: str) -> str:
    def repl(m: re.Match) -> str:
        ref = m.group(1)
        path = SITE / ref
        if not path.is_file():
            print(f"  skip missing font: {ref}", file=sys.stderr)
            return m.group(0)
        return f'url("{data_url(path)}")'

    return re.sub(r'url\("(assets/[^"]+)"\)', repl, html)


def patch_act_covers(html: str) -> str:
    covers_dir = SITE / "assets" / "covers"
    if not covers_dir.is_dir():
        return html
    entries = []
    for p in sorted(covers_dir.glob("*.jpg")):
        entries.append(f'    "{p.stem}": "{data_url(p)}"')
    map_body = ",\n".join(entries)
    inject = f"  const COVER_BY_ID = {{\n{map_body}\n  }};\n"
    old = "  const acts = actsRaw.map(a => ({\n    ...a,\n    cover: `assets/covers/${a.id}.jpg`,\n    repeatMonthDays:"
    new = inject + "  const acts = actsRaw.map(a => ({\n    ...a,\n    cover: COVER_BY_ID[a.id] || '',\n    repeatMonthDays:"
    if old not in html:
        print("  warn: act cover patch pattern not found", file=sys.stderr)
        return html
    return html.replace(old, new, 1)


def main() -> None:
    print("Reading index.html …")
    html = INDEX.read_text(encoding="utf-8")

    print("Inlining scripts …")
    html = inline_scripts(html)

    print("Patching activity cover paths …")
    html = patch_act_covers(html)

    print("Embedding font URLs in CSS …")
    html = embed_css_asset_urls(html)

    banner = (
        "<!-- interest-group standalone bundle · open via double-click (file://) -->\n"
        "<!-- generated by site/build_standalone.py · do not edit by hand -->\n"
    )
    if "<!-- interest-group standalone" not in html:
        html = html.replace("<!DOCTYPE html>", "<!DOCTYPE html>\n" + banner, 1)

    OUT.write_text(html, encoding="utf-8")
    size_mb = OUT.stat().st_size / (1024 * 1024)
    print(f"Wrote {OUT} ({size_mb:.1f} MB)")


if __name__ == "__main__":
    main()
