import { chromium } from 'playwright';
import path from 'node:path';
import fs from 'node:fs';
import { fileURLToPath } from 'node:url';
const dir = path.dirname(fileURLToPath(import.meta.url));
const out = path.join(dir, '..', 'site', 'preview');
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 900 }, deviceScaleFactor: 2 });
const errors = [];
page.on('pageerror', e => errors.push(e.message));
await page.goto('http://127.0.0.1:8080/', { waitUntil: 'networkidle' });
await page.waitForTimeout(3000);
await page.getByText('PC 管理端').click();
await page.waitForTimeout(1500);
await page.getByText('活动管理', { exact: true }).first().click();
await page.waitForTimeout(1500);
await page.screenshot({ path: path.join(out, '03-admin-acts.png') });
console.log('ERRORS', errors.length, errors.join('|'));
await browser.close();
