import { chromium } from 'playwright';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const dir = path.dirname(fileURLToPath(import.meta.url));
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 900 }, deviceScaleFactor: 2 });
const errors = [];
page.on('pageerror', e => errors.push(e.message));
await page.goto('http://127.0.0.1:8080/', { waitUntil: 'networkidle' });
await page.waitForTimeout(2500);
await page.getByText('PC 管理端').click();
await page.waitForTimeout(900);
await page.getByRole('button', { name: /活动管理/ }).first().click();
await page.waitForTimeout(900);
await page.getByText('云栖谷溪行 · 看日出系列 ②').click();
await page.waitForTimeout(900);
const before = await page.getByText('待审核申请 (2)').count();
await page.getByRole('button', { name: '通过' }).first().click();
await page.waitForTimeout(600);
const after = await page.getByText('待审核申请 (1)').count();
const toast = await page.getByText('已通过 罗茜 的报名').count();
console.log('pending before:', before > 0);
console.log('pending after approve:', after > 0);
console.log('toast shown:', toast > 0);
console.log('ERRORS', errors.length, errors.join('|'));
await browser.close();
